//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System.Web;
namespace Sample.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;
    using System.Drawing;
    
    
   
    using static System.Net.Mime.MediaTypeNames;

    public partial class Employees
    {
        public int EMpl_ID { get; set; }
        [Required(ErrorMessage = "This field is required.")]
        public string Name { get; set; }
        public Nullable<int> Salary { get; set; }
        public string image { get; set; }

        [NotMapped]
        public HttpPostedFileBase ImageUpload { get; set; }

        public Employees()
        {
            image = "~/AppFiles/Images/default.png";
        }
    }
}     


